spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/appointment-mgmt-svc'
    username: postgres
    password: Admin1234!
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
logging:
  level:
    root: INFO
jwt:
  secret: secretabc123
  expiration: 24
sorting:
  order: desc
  column: createdBy